M48
; DRILL file KiCad 10.0.3 date 2026-06-10T11:11:07
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-10T11:11:07+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X209.169Y-93.534
X209.169Y-99.314
T2
X199.974Y-126.206
M30
